language: c++
sudo: false

addons:
    apt:
        packages:
            - g++-6
            - llvm-dev
            - flex
            - bison
        sources: &sources
            - ubuntu-toolchain-r-test

cache:
    directories:
        - ${TRAVIS_BUILD_DIR}/deps/llvm-3.8.0

matrix:
    include:
        - os: osx
          env: UTEST=true COMPILER=g++-6

        - os: linux
          dist: trusty
          env: UTEST=true COMPILER=g++-6

install:
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - LLVM_VERSION=3.8.0
    - export LLVM_DIR=${DEPS_DIR}/llvm-${LLVM_VERSION}
    - mkdir -p ${DEPS_DIR} && pushd ${DEPS_DIR}

    - |
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}

    - |
      LLVM_URL="http://llvm.org/releases/${LLVM_VERSION}/llvm-${LLVM_VERSION}.src.tar.xz"
      mkdir -p ${LLVM_DIR} ${LLVM_DIR}/build
      travis_retry wget --quiet -O - ${LLVM_URL}      | tar --strip-components=1 -xJ -C ${LLVM_DIR}
      (pushd ${LLVM_DIR}/build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${LLVM_DIR}/install -DCMAKE_CXX_COMPILER=$COMPILER && make -j2 && make install && popd)

    - popd

script:
    ${TRAVIS_BUILD_DIR}/compile.sh
