language: c++
sudo: false

addons:
    apt:
        packages:
            - g++-6
            - llvm-dev
            - flex
            - bison
        sources: &sources
            - ubuntu-toolchain-r-test

cache:
    directories:
        - ${TRAVIS_BUILD_DIR}/deps/bison-3.0.4
        - ${TRAVIS_BUILD_DIR}/deps/llvm-3.8.0

matrix:
    include:
        - os: osx
          env: UNIT_TEST=true COMPILER=g++-6

        - os: linux
          env: UNIT_TEST=true COMPILER=g++-6

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc6; fi

install:
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - LLVM_VERSION=3.8.0
    - export LLVM_DIR=${DEPS_DIR}/llvm-${LLVM_VERSION}
    - export BISON_DIR=${DEPS_DIR}/bison-3.0.4
    - mkdir -p ${DEPS_DIR} && pushd ${DEPS_DIR}

    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux"  ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
        mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      else
        if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
      fi

    - |
      BISON_URL="http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.xz"
      mkdir -p ${BISON_DIR}
      travis_retry wget --quiet -O - ${BISON_URL}      | tar --strip-components=1 -xJ -C ${BISON_DIR}
      mkdir -p ${BISON_DIR}/leinstall
      (pushd ${BISON_DIR} && ./configure --prefix="${BISON_DIR}/leinstall" && make && make install && popd)


    - |
      LLVM_URL="http://llvm.org/releases/${LLVM_VERSION}/llvm-${LLVM_VERSION}.src.tar.xz"
      mkdir -p ${LLVM_DIR} ${LLVM_DIR}/build
      travis_retry wget --quiet -O - ${LLVM_URL}      | tar --strip-components=1 -xJ -C ${LLVM_DIR}
      (pushd ${LLVM_DIR}/build && cmake .. -DLLVM_ENABLE_RTTI=true -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${LLVM_DIR}/install -DCMAKE_CXX_COMPILER=$COMPILER && make -j2 && make install && popd)
    - popd

script:
    ${TRAVIS_BUILD_DIR}/compile.sh -c
